<?php

//if request not from byui.projectpine.com then use default

if(str_contains($_SERVER['HTTP_REFERER'], "byui.projectpine.com") == false) {
    //401 unauthorized
    header('HTTP/1.1 401 Unauthorized');
    header('Content-Type: application/json');
    echo json_encode(array("error" => "Unauthorized", "message" => "generated by byui.projectpine.com/api_proxy.php"));
    exit;
}


$request = $_SERVER['QUERY_STRING']??"";

if(empty($request)) $request = "q=London,uk&units=metric";

$apiKey = "d3dbafb2f2288266046409ab37fc5787";//"d817254dbca7b1a6fea4b94cffa47e2e";

$url = "https://api.openweathermap.org/data/2.5/weather?appid=${apiKey}&" . $request;

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
$output = curl_exec($ch);
curl_close($ch);

header('Content-Type: application/json');

echo $output;
